# Python Assignment: Week 1 Solutions

**Student Name:** Meghana Prakash Naik

**Program:** B.Tech data CSE(data science)

This document presents the complete solutions and explanations for all questions in the Week 1 Python Assignment.

## Q1. Differentiate between Python's `is` and `==` operators.

### Explanation

`==` checks if values are equal. `is` checks if two variables refer to the *exact same object* in memory.

**Demonstration**

```python
list1 = [10, 20, 30]
list2 = [10, 20, 30]
list3 = list1 # list3 points to the same object as list1

print(f"list1 == list2: {list1 == list2}") # True (same content)
print(f"list1 is list2: {list1 is list2}")   # False (different objects)
print(f"list1 is list3: {list1 is list3}")   # True (same object)
```

### Output

```
list1 == list2: True
list1 is list2: False
list1 is list3: True
```
## Q2. Categorize the following Python data types as Mutable or Immutable.

| Data Type    | Mutability    |
|--------------|---------------|
| List         | Mutable       |
| Tuple        | Immutable     |
| Set          | Mutable       |
| Dictionary   | Mutable       |
| String       | Immutable     |
| Integer      | Immutable     |
| Float        | Immutable     |
| Boolean      | Immutable     |
| Frozenset    | Immutable     |

### Significance

Immutable objects cannot be changed after creation. This helps prevent accidental modifications and makes them safe for uses like dictionary keys.

## Q3. Determine the result of the following Python expression:

```python
print(0.1 + 0.2 == 0.3)
```

### Output

```
False
```

### Reason

Floating-point numbers (like 0.1, 0.2, 0.3) can't always be precisely represented in binary, leading to slight inaccuracies in calculations.

## Q4. Under what circumstances would a tuple be preferred over a list?

### When to use Tuples

Tuples are better when:
1.  **Data should not change:** For fixed collections (e.g., coordinates, database records).
2.  **Used as dictionary keys or set elements:** Tuples are hashable because they are immutable.
3.  **Returning multiple values from a function:** Provides an ordered, unchangeable collection.

## Q5. Explain why dictionary lookups typically achieve O(1) time complexity, whereas searching in a list is O(n).

### Complexity Difference

*   **Dictionaries:** Use hash tables for direct access. On average, finding an item is constant time (O(1)), regardless of dictionary size.
*   **Lists:** Require scanning elements one by one. Finding an item takes linear time (O(n)), proportional to the list's size.

## Q6. Compare and contrast `range()` and `numpy.arange()`.

| Feature         | `range()` (Built-in)        | `numpy.arange()` (NumPy)               |
|-----------------|-----------------------------|----------------------------------------|
| **Output**      | Range object (iterator)     | NumPy array (stores all numbers)       |
| **Data Types**  | Integers only               | Integers, floats, custom step          |
| **Use Case**    | Simple loops                | Numerical operations, array creation   |
| **Memory**      | Efficient (generates on demand) | More memory for large arrays           |

## Q7. Explain the distinctions between `append()`, `extend()`, and `insert()` methods for lists.

Initial list: `my_list = [10, 20, 30]`
Elements to add: `elements_to_add = [40, 50]`

### `append()`
Adds a single element to the end. If you append a list, it adds the list as one item.
```python
current_list = list(my_list)
current_list.append(elements_to_add)
print(f"After append(): {current_list}")
```
Output: `[10, 20, 30, [40, 50]]`

### `extend()`
Adds all elements from an iterable to the end of the list.
```python
current_list = list(my_list)
current_list.extend(elements_to_add)
print(f"After extend(): {current_list}")
```
Output: `[10, 20, 30, 40, 50]`

### `insert()`
Inserts a single element at a specified index.
```python
current_list = list(my_list)
current_list.insert(1, elements_to_add) # Insert at index 1
print(f"After insert(1, ...): {current_list}")
```
Output: `[10, [40, 50], 20, 30]`

## Q8. Analyze the results of extended iterable unpacking for variables `x`, `y`, and `z`.

Given `x, *y, z = [100, 200, 300, 400, 500]`

Result:
```
x = 100
y = [200, 300, 400]
z = 500
```

*   **For `[100, 200]`:** `x = 100`, `y = []`, `z = 200`
*   **For `[100]`:** `ValueError` (needs at least two elements for `x` and `z`).

## Q9. Describe the functionality of the following arithmetic operators in Python.

| Operator | Description                    | Example (`-7`, `2`) | Result    |
|----------|--------------------------------|---------------------|-----------|
| `/`      | Division (float)               | `-7 / 2`            | `-3.5`    |
| `//`     | Floor Division (rounds down)   | `-7 // 2`           | `-4`      |
| `%`      | Modulo (remainder)             | `-7 % 2`            | `1`       |
| `**`     | Exponentiation                 | `(-7) ** 2`         | `49`      |

---

## Q10. Provide reasons for NumPy's superior performance compared to standard Python lists.

### NumPy's Performance Edge

1.  **Memory:** Contiguous memory storage, better cache use.
2.  **C Code:** Core operations are optimized C/Fortran code, not slow Python loops.
3.  **Vectorization:** Operates on entire arrays at once, removing Python loop overhead.
4.  **Fixed Type:** Elements are all same type, simplifies processing.

## Q11. Predict the output. Why does the second line behave differently?

### Code

```python
matrix1 = [[0] * 3 for _ in range(3)]
matrix2 = [[0] * 3] * 3

matrix1[0][0] = 99
matrix2[0][0] = 99

print(matrix1)
print(matrix2)
```

### Predicted Output

```
[[99, 0, 0], [0, 0, 0], [0, 0, 0]]

[[99, 0, 0], [99, 0, 0], [99, 0, 0]]
```

### Explanation

`matrix1` creates distinct inner lists. `matrix2` creates multiple references to the *same* inner list.

In [35]:
# Q16 - Demonstrating Number Swapping Techniques

val1 = 30
val2 = 40

print("Initial values (Arithmetic): val1 =", val1, ", val2 =", val2)


val1 = val1 + val2
val2 = val1 - val2
val1 = val1 - val2

print("After Arithmetic Swap: val1 =", val1, ", val2 =", val2)
print()


num_a = 15
num_b = 25

print("Initial values (XOR): num_a =", num_a, ", num_b =", num_b)


num_a = num_a ^ num_b
num_b = num_a ^ num_b
num_a = num_a ^ num_b

print("After XOR Swap: num_a =", num_a, ", num_b =", num_b)
print()


var_x = 19
var_y = 78

print("Initial values (Tuple Unpacking): var_x =", var_x, ", var_y =", var_y)

# Perform the swap elegantly with tuple unpacking
var_x, var_y = var_y, var_x

print("After Tuple Unpacking Swap: var_x =", var_x, ", var_y =", var_y)

Initial values (Arithmetic): val1 = 30 , val2 = 40
After Arithmetic Swap: val1 = 40 , val2 = 30

Initial values (XOR): num_a = 15 , num_b = 25
After XOR Swap: num_a = 25 , num_b = 15

Initial values (Tuple Unpacking): var_x = 19 , var_y = 78
After Tuple Unpacking Swap: var_x = 78 , var_y = 19


In [2]:
# Q17 Swiggy Order Calculator

price = float(input("Enter Item Price : "))
quantity = int(input("Enter Quantity : "))

subtotal = price * quantity
gst = subtotal * 0.18

if subtotal < 500:
    delivery = 40
else:
    delivery = 0

total = subtotal + gst + delivery
print()

print("Subtotal :", subtotal)
print("GST :", gst)
print("Delivery :", delivery)
print("---------------------")
print("Total :", total)

Enter Item Price : 90
Enter Quantity : 56

Subtotal : 5040.0
GST : 907.1999999999999
Delivery : 0
---------------------
Total : 5947.2


In [3]:
# Q18 Temperature Converter

temperature = float(input("Enter Temperature : "))
unit = input("Enter Unit (C/F) : ").upper()

if unit == "C":
    fahrenheit = (temperature * 9/5) + 32
    print("Temperature =", round(fahrenheit,2), "F")
elif unit == "F":
    celsius = (temperature - 32) * 5/9
    print("Temperature =", round(celsius,2), "C")
else:
    print("Invalid Unit")

Enter Temperature : 40
Enter Unit (C/F) : c
Temperature = 104.0 F


## Q15. Predict the output

```python
print(0 or 5)
print(5 or 0)
print(None or "hello")
print(0 and 5)
print(5 and 10)
print([] or "default")
print([0] or "default")
```

### Predicted Output

```
5
5
hello
0
10
default
[0]
```



In [4]:
# Q20 Smart Input Parser

value = input("Enter a Value : ")
try:
    number = int(value)
    print("Detected Type : Integer")
    print("Value :", number)
except ValueError:
    try:
        number = float(value)
        print("Detected Type : Float")
        print("Value :", number)
    except ValueError:
        print("Detected Type : String")
        print("Value :", value)

Enter a Value : 89
Detected Type : Integer
Value : 89


In [5]:
# Q21 - Indian Income Tax Calculator (New Regime FY 2024-25)

income = float(input("Enter Annual Income : "))

tax = 0
if income > 1500000:
    tax += (income - 1500000) * 0.30
    income = 1500000
if income > 1200000:
    tax += (income - 1200000) * 0.20
    income = 1200000
if income > 1000000:
    tax += (income - 1000000) * 0.15
    income = 1000000
if income > 700000:
    tax += (income - 700000) * 0.10
    income = 700000
if income > 300000:
    tax += (income - 300000) * 0.05

print("\nTotal Tax Payable : ₹", round(tax, 2))

Enter Annual Income : 600000

Total Tax Payable : ₹ 15000.0


In [6]:
# Q22 - PAN Card Validation

pan = input("Enter PAN Number : ")

if len(pan) != 10:
    print("Invalid PAN - Length should be 10")
elif not pan[:5].isalpha() or not pan[:5].isupper():
    print("Invalid PAN - First 5 characters should be uppercase letters")
elif not pan[5:9].isdigit():
    print("Invalid PAN - Middle 4 characters should be digits")
elif not pan[9].isalpha() or not pan[9].isupper():
    print("Invalid PAN - Last character should be uppercase")
else:
    print("Valid PAN")

Enter PAN Number : PANCA3108M
Valid PAN


In [7]:
# Q23 - BESCOM Electricity Bill

units = float(input("Enter Units Consumed : "))

if units <= 50:
    energy = units * 4.10
elif units <= 100:
    energy = 50 * 4.10 + (units - 50) * 5.55
elif units <= 200:
    energy = 50 * 4.10 + 50 * 5.55 + (units - 100) * 7.10
else:
    energy = 50 * 4.10 + 50 * 5.55 + 100 * 7.10 + (units - 200) * 8.15

fixed_charge = 110
subtotal = energy + fixed_charge
tax = subtotal * 0.06
total = subtotal + tax

print("\nEnergy Charge :", round(energy,2))
print("Fixed Charge :", fixed_charge)
print("Government Tax :", round(tax,2))
print("-------------------------")
print("Total Bill :", round(total,2))

Enter Units Consumed : 78

Energy Charge : 360.4
Fixed Charge : 110
Government Tax : 28.22
-------------------------
Total Bill : 498.62


In [8]:
# Q24 - Cricket Strike Rate

runs = int(input("Enter Runs : "))
balls = int(input("Enter Balls Faced : "))

if balls == 0:
    print("Strike Rate cannot be calculated.")
else:
    strike_rate = (runs / balls) * 100
    print("Strike Rate =", round(strike_rate,2))
    if strike_rate > 150:
        print("Explosive (T20 Finisher)")
    elif strike_rate > 100:
        print("Aggressive (Top Order T20)")
    elif strike_rate >= 75:
        print("Steady (ODI Anchor)")
    else:
        print("Defensive (Test Match)")

Enter Runs : 56
Enter Balls Faced : 12
Strike Rate = 466.67
Explosive (T20 Finisher)


In [9]:
# Q25 - BMI Calculator

weight = float(input("Enter Weight (kg) : "))
height = float(input("Enter Height (cm) : "))

height = height / 100
bmi = weight / (height ** 2)

print("\nBMI =", round(bmi,2))
if bmi < 18.5:
    print("Underweight")
elif bmi <= 22.9:
    print("Normal")
elif bmi <= 24.9:
    print("Overweight")
elif bmi <= 29.9:
    print("Obese Class I")
else:
    print("Obese Class II")

Enter Weight (kg) : 38
Enter Height (cm) : 162

BMI = 14.48
Underweight


In [37]:
# Q26 - Number Pattern

n = int(input("Enter N : "))

for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

Enter N : 12
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 
1 2 3 4 5 6 
1 2 3 4 5 6 7 
1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 9 10 
1 2 3 4 5 6 7 8 9 10 11 
1 2 3 4 5 6 7 8 9 10 11 12 


In [36]:
# Q27 - Number Diamond Pattern

n = int(input("Enter N : "))

# Upper Half
for i in range(1, n + 1):
    print(" " * (n - i), end="")
    for j in range(1, i + 1):
        print(j, end=" ")
    for j in range(i - 1, 0, -1):
        print(j, end=" ")
    print()

# Lower Half
for i in range(n - 1, 0, -1):
    print(" " * (n - i), end="")
    for j in range(1, i + 1):
        print(j, end=" ")
    for j in range(i - 1, 0, -1):
        print(j, end=" ")
    print()

Enter N : 6
     1 
    1 2 1 
   1 2 3 2 1 
  1 2 3 4 3 2 1 
 1 2 3 4 5 4 3 2 1 
1 2 3 4 5 6 5 4 3 2 1 
 1 2 3 4 5 4 3 2 1 
  1 2 3 4 3 2 1 
   1 2 3 2 1 
    1 2 1 
     1 


In [12]:
# Q28 - Hollow Square Pattern

n = int(input("Enter N : "))

for i in range(n):
    for j in range(n):
        if i == 0 or i == n - 1 or j == 0 or j == n - 1:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

Enter N : 5
* * * * * 
*       * 
*       * 
*       * 
* * * * * 


In [13]:
# Q29 - Pascal's Triangle

rows = 5

for i in range(rows):
    number = 1
    print(" " * (rows - i), end="")
    for j in range(i + 1):
        print(number, end=" ")
        number = number * (i - j) // (j + 1)
    print()

     1 
    1 1 
   1 2 1 
  1 3 3 1 
 1 4 6 4 1 


In [14]:
# Q30 - Character Pattern

n = int(input("Enter N : "))
for i in range(1, n + 1):
    for j in range(i):
        print(chr(65 + j), end=" ")
    print()

Enter N : 5
A 
A B 
A B C 
A B C D 
A B C D E 


In [15]:
# Q31 - Armstrong Numbers between 1 and 9999

count = 0

print("Armstrong Numbers:")
for num in range(1, 10000):

    temp = num
    digits = len(str(num))
    total = 0
    while temp > 0:
        digit = temp % 10
        total += digit ** digits
        temp //= 10
    if total == num:
        print(num, end=" ")
        count += 1
print("\n")
print("Total Armstrong Numbers =", count)

Armstrong Numbers:
1 2 3 4 5 6 7 8 9 153 370 371 407 1634 8208 9474 

Total Armstrong Numbers = 16


In [16]:
# Q32 - Fibonacci Series

n = int(input("Enter Number of Terms : "))

first = 0
second = 1
total = 0

if n == 0:
    print("Sum = 0")
elif n == 1:
    print(first)
    print("Sum =", first)
else:
    print("Fibonacci Series:")
    for i in range(n):
        print(first, end=" ")
        total += first
        next_num = first + second
        first = second
        second = next_num
    print("\nSum =", total)

Enter Number of Terms : 7
Fibonacci Series:
0 1 1 2 3 5 8 
Sum = 20


In [17]:
# Q33 - Prime Number and Sum of Prime Numbers

n = int(input("Enter a Number : "))
is_prime = True

if n < 2:
    is_prime = False
else:
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            is_prime = False
            break

if is_prime:
    print(n, "is a Prime Number")
else:
    print(n, "is not a Prime Number")

prime_sum = 0

for num in range(2, n + 1):
    prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            prime = False
            break
    if prime:
        prime_sum += num

print("Sum of Prime Numbers =", prime_sum)

Enter a Number : 7
7 is a Prime Number
Sum of Prime Numbers = 17


In [18]:
# Q34 - Reverse Number and Palindrome

number = int(input("Enter Number : "))

if number < 0:
    print("Negative numbers are not palindrome.")
else:
    original = number
    reverse = 0
    while number > 0:
        digit = number % 10
        reverse = reverse * 10 + digit
        number //= 10
    print("Reversed Number =", reverse)

    if original == reverse:
        print("Palindrome")
    else:
        print("Not Palindrome")

Enter Number : 7
Reversed Number = 7
Palindrome


In [19]:
# Q35 - HCF and LCM

a = int(input("Enter First Number : "))
b = int(input("Enter Second Number : "))

x = a
y = b

while y != 0:
    remainder = x % y
    x = y
    y = remainder

hcf = x
lcm = (a * b) // hcf

print("HCF =", hcf)
print("LCM =", lcm)

Enter First Number : 7
Enter Second Number : 56
HCF = 7
LCM = 56


In [20]:
# Q36 - String Scanner

text = input("Enter a Sentence : ")

characters = 0
words = len(text.split())
vowels = 0
consonants = 0
digits = 0
spaces = 0
special = 0

for ch in text:

    characters += 1

    if ch.lower() in "aeiou":
        vowels += 1

    elif ch.isalpha():
        consonants += 1

    elif ch.isdigit():
        digits += 1

    elif ch.isspace():
        spaces += 1

    else:
        special += 1

print("\nCharacters :", characters)
print("Words :", words)
print("Vowels :", vowels)
print("Consonants :", consonants)
print("Digits :", digits)
print("Spaces :", spaces)
print("Special Characters :", special)

Enter a Sentence : i am a student

Characters : 14
Words : 4
Vowels : 5
Consonants : 6
Digits : 0
Spaces : 3
Special Characters : 0


In [21]:
# Q37 - Student Marks Analysis

marks = list(map(int, input("Enter 10 Marks : ").split()))

maximum = max(marks)
minimum = min(marks)
average = sum(marks) / len(marks)

count = 0

for mark in marks:

    if mark > average:
        count += 1

temp = marks.copy()

temp.remove(maximum)

second_highest = max(temp)

print("\nMaximum =", maximum)
print("Minimum =", minimum)
print("Average =", round(average,2))
print("Above Average =", count)
print("Second Highest =", second_highest)

Enter 10 Marks :  77 88 87 76 65 54 98 86 85 84 

Maximum = 98
Minimum = 54
Average = 80.0
Above Average = 6
Second Highest = 88


In [22]:
# Q38 - Word Frequency

review = input("Enter Review : ").lower().split()

frequency = {}

for word in review:

    if word in frequency:
        frequency[word] += 1
    else:
        frequency[word] = 1

sorted_words = sorted(frequency.items(), key=lambda x: x[1], reverse=True)
print()

for word, count in sorted_words:
    print(word, ":", count)

print("\nMost Frequent Word :", sorted_words[0][0])
print("Count :", sorted_words[0][1])

Enter Review : it is good

it : 1
is : 1
good : 1

Most Frequent Word : it
Count : 1


In [23]:
# Q39 - Indian States CRUD

states = {
    "Karnataka": "Bengaluru",
    "Maharashtra": "Mumbai",
    "Tamil Nadu": "Chennai",
    "Kerala": "Thiruvananthapuram",
    "Telangana": "Hyderabad"
}

while True:

    print("\n1. Add")
    print("2. Update")
    print("3. Delete")
    print("4. Search")
    print("5. Display")
    print("6. Exit")

    choice = int(input("Enter Choice : "))

    if choice == 1:

        state = input("State : ")
        capital = input("Capital : ")
        states[state] = capital
    elif choice == 2:
        state = input("State : ")
        if state in states:
            states[state] = input("New Capital : ")
        else:
            print("State Not Found")
    elif choice == 3:
        state = input("State : ")
        states.pop(state, None)
    elif choice == 4:
        state = input("State : ")
        print(states.get(state, "Not Found"))
    elif choice == 5:
        for state in sorted(states):
            print(state, ":", states[state])
    elif choice == 6:
        print("Program Ended")
        break
    else:
        print("Invalid Choice")


1. Add
2. Update
3. Delete
4. Search
5. Display
6. Exit
Enter Choice : 1
State : mysuru
Capital : srirangpatna

1. Add
2. Update
3. Delete
4. Search
5. Display
6. Exit
Enter Choice : 5
Karnataka : Bengaluru
Kerala : Thiruvananthapuram
Maharashtra : Mumbai
Tamil Nadu : Chennai
Telangana : Hyderabad
mysuru : srirangpatna

1. Add
2. Update
3. Delete
4. Search
5. Display
6. Exit
Enter Choice : 3
State : karnataka

1. Add
2. Update
3. Delete
4. Search
5. Display
6. Exit
Enter Choice : 6
Program Ended


In [24]:
# Q40 - Set Operations

section_A = {"Python", "Java", "C++", "SQL"}

section_B = {"Java", "JavaScript", "Python", "Go", "SQL"}

print("Common Languages :", section_A & section_B)
print("Only Section A :", section_A - section_B)
print("Only Section B :", section_B - section_A)
print("All Languages :", section_A | section_B)
print("Symmetric Difference :", section_A ^ section_B)

Common Languages : {'Java', 'Python', 'SQL'}
Only Section A : {'C++'}
Only Section B : {'Go', 'JavaScript'}
All Languages : {'Go', 'Python', 'C++', 'JavaScript', 'SQL', 'Java'}
Symmetric Difference : {'Go', 'C++', 'JavaScript'}


In [25]:
# Q41 - TCS Stock Price Analysis

prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)
days = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

maximum = max(prices)
minimum = min(prices)

print("Maximum Price :", maximum)
print("Day :", days[prices.index(maximum)])

print()

print("Minimum Price :", minimum)
print("Day :", days[prices.index(minimum)])

average = sum(prices) / len(prices)

print()

print("Average Price :", round(average, 2))

gain = 0
gain_day = ""

for i in range(1, len(prices)):
    difference = prices[i] - prices[i - 1]
    if difference > gain:
        gain = difference
        gain_day = days[i - 1] + " to " + days[i]
print()

print("Biggest Gain :", gain)
print("Between :", gain_day)

volatility = 0

for i in range(1, len(prices)):
    volatility += abs(prices[i] - prices[i - 1])
print("Total Volatility :", volatility)

Maximum Price : 4055
Day : Sun

Minimum Price : 3845
Day : Mon

Average Price : 3949.29

Biggest Gain : 77
Between : Wed to Thu
Total Volatility : 286


In [26]:
# Q42 - Duplicate Finder

numbers = [12, 45, 12, 78, 45, 90, 15, 22, 78, 33,
           90, 65, 44, 22, 11, 87, 65, 99, 10, 55]

frequency = {}

for num in numbers:

    if num in frequency:
        frequency[num] += 1
    else:
        frequency[num] = 1

print("Unique Numbers")
print(set(numbers))
print()

duplicates = []
single = []

for key, value in frequency.items():
    if value > 1:
        duplicates.append(key)
    else:
        single.append(key)

print("Duplicate Numbers :", duplicates)
print("Appearing Exactly Once :", single)

Unique Numbers
{33, 65, 99, 10, 11, 12, 45, 78, 15, 44, 55, 22, 87, 90}

Duplicate Numbers : [12, 45, 78, 90, 22, 65]
Appearing Exactly Once : [15, 33, 44, 11, 87, 99, 10, 55]


In [27]:
# Q43 - Smart Palindrome Checker

sentence = input("Enter Sentence : ")

clean = ""

for ch in sentence:
    if ch.isalnum():
        clean += ch.lower()
if clean == clean[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")

Enter Sentence : this is a language
Not Palindrome


In [28]:
# Q44 - Manual Title Case

sentence = input("Enter Sentence : ")
words = sentence.lower().split()
result = ""

for word in words:
    result += word[0].upper() + word[1:] + " "
print(result)

Enter Sentence : c language is easy
C Language Is Easy 


In [29]:
# Q45 - Caesar Cipher

message = input("Enter Message : ")
shift = int(input("Enter Shift Value : "))
encrypted = ""

for ch in message:
    if ch.isalpha():
        if ch.isupper():
            encrypted += chr((ord(ch) - 65 + shift) % 26 + 65)
        else:
            encrypted += chr((ord(ch) - 97 + shift) % 26 + 97)
    else:
        encrypted += ch

print()
print("Encrypted Message")
print(encrypted)

Enter Message : hi how are you?
Enter Shift Value : 5

Encrypted Message
mn mtb fwj dtz?


In [30]:
# Q46 - GST Calculator

def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if gst_inclusive:
        base = amount / (1 + gst_rate / 100)
        gst = amount - base
        total = amount
    else:
        base = amount
        gst = amount * gst_rate / 100
        total = amount + gst
    return round(base,2), round(gst,2), round(total,2)


print(calculate_gst(1000))
print(calculate_gst(1180, gst_inclusive=True))
print(calculate_gst(500, gst_rate=5))

(1000, 180.0, 1180.0)
(1000.0, 180.0, 1180)
(500, 25.0, 525.0)


In [31]:
# Q47 - Recursive Power Function

def power(base, exponent):
    if exponent == 0:
        return 1
    elif exponent < 0:
        return 1 / power(base, -exponent)
    else:
        return base * power(base, exponent - 1)

print(power(2,10))
print(power(5,0))
print(power(3,-2))

1024
1
0.1111111111111111


In [32]:
# Q48 - Identity Matrix

import numpy as np

identity = np.eye(5)
print("Identity Matrix")
print(identity)
matrix = identity * 10
print()

print(matrix)

transpose = matrix.T
print()
print(transpose)
print()

print("Diagonal Sum =", np.trace(matrix))
print("Total Sum =", np.sum(matrix))

Identity Matrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Diagonal Sum = 50.0
Total Sum = 50.0


In [33]:
# Q49 - Zomato Weekly Sales

import numpy as np

sales = np.array([12000,18500,14200,22100,19800,35200,28400])
days = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
print("Total Sales :", np.sum(sales))
print("Average Sales :", np.mean(sales))
print("Highest Sales Day :", days[np.argmax(sales)])
print("Above Average Days :", np.sum(sales > np.mean(sales)))

growth = ((sales[-1] - sales[0]) / sales[0]) * 100
print("Growth Percentage :", round(growth,2), "%")
changes = ((sales[1:] - sales[:-1]) / sales[:-1]) * 100

print()

print("Day-wise Percentage Change")
print(changes)

Total Sales : 150200
Average Sales : 21457.14285714286
Highest Sales Day : Sat
Above Average Days : 3
Growth Percentage : 136.67 %

Day-wise Percentage Change
[ 54.16666667 -23.24324324  55.63380282 -10.40723982  77.77777778
 -19.31818182]


In [34]:
# Q50 - Border Pattern using NumPy

import numpy as np

array = np.ones((5,5), dtype=int)
array[1:4,1:4] = 0

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
